### Create new user account
POST http://localhost:5000/user/create
Content-type: application/json

{
    "fullName": "Ferrari",
    "mobileNumber": 35441345,
    "status": "Free", 
    "photoUrl":"https://www.ball.com"

}


### Edit user profile
POST http://localhost:5000/user/5fa7b8cde2908605dbaea28d/update
Content-type: application/json

{
    "fullName": "Ferrari varikkottil",
    "mobileNumber": 95447618487,
    "status": "Busy", 
    "photoUrl":"https://www.google.com"

}

### Delete user account
POST http://localhost:5000/user/5fa7b8cde2908605dbaea28d/delete
Content-type: application/json



### Create a new group
POST http://localhost:5000/group/create
Content-type: application/json

{

    "groupName": "Ferrari",
    "photoUrl": "https://www.photo.com"
}

### Add member to group
POST http://localhost:5000/group/5fa7b8ffe2908605dbaea28e/addmember
Content-type: application/json

{

    "userId": "5fa7b8cde2908605dbaea28d"
}


### Delete Group 
POST http://localhost:5000/group/5fa7b8ffe2908605dbaea28e/delete
Content-type: application/json



### Edit Group Details
POST http://localhost:5000/group/5fa7885f6fec9a02f37d6358/update
Content-type: application/json

{
    "groupName": "Apple Boys",
    "photoUrl":"https://www.applesgroup.com"

}
