### Create new user account
POST http://localhost:5000/user/create
Content-type: application/json

{
    "fullName": "Ferrari",
    "mobileNumber": 35441345,
    "status": "Free", 
    "photoUrl":"https://www.ball.com"

}


### Show all users
GET http://localhost:5000/user/users

### Send a message to one User
POST http://localhost:5000/user/5fa785b066007202a9b00819/message/new
Content-Type: application/json

{
    "message": "Hai, My friend",
    "sender": "5fa785ab66007202a9b00818"

}

### Edit user profile
POST http://localhost:5000/user/5fa7b8cde2908605dbaea28d/update
Content-type: application/json

{
    "fullName": "Ferrari varikkottil",
    "mobileNumber": 95447618487,
    "status": "Busy", 
    "photoUrl":"https://www.google.com"

}

### Delete user account
POST http://localhost:5000/user/5fa7b8cde2908605dbaea28d/delete
Content-type: application/json



### Create a new group
POST http://localhost:5000/group/create
Content-type: application/json

{

    "groupName": "Ferrari",
    "photoUrl": "https://www.photo.com"
}

### Show all groups
GET http://localhost:5000/group/groups


### Add member to group
POST http://localhost:5000/group/5fa7885f6fec9a02f37d6358/addmember
Content-type: application/json

{

    "userId": "5fa785ab66007202a9b00818"
}


### Send a message to the group
POST http://localhost:5000/group/5fa7885f6fec9a02f37d6358/message/new
Content-Type: application/json

{
    "message": "Hai, Folks",
    "sender": "5fa785ab66007202a9b00818"

}

### Delete Group 
POST http://localhost:5000/group/5fa7b8ffe2908605dbaea28e/delete
Content-type: application/json



### Edit Group Details
POST http://localhost:5000/group/5fa7885f6fec9a02f37d6358/update
Content-type: application/json

{
    "groupName": "Apple Boys",
    "photoUrl":"https://www.applesgroup.com"

}
