### Create new user account | Register
POST http://localhost:5000/account/create
Content-type: application/json

{
    "fullName": "2nd account",
    "password": "newPassword",
    "username": 9876543210,
    "status": "dev", 
    "photoUrl":"https://www.dev.com"

}


### Login to your user account | Login
POST http://localhost:5000/account/login
Content-type: application/json

{
    "password": "newPassword",
    "username": "9876543210"

}

### Show all users
GET http://localhost:5000/user/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6OTg3NjU0MzIxMCwiaWQiOiI2MDE5MzY3ZWQwN2Y4YzAyZTg5MmM1OTUiLCJpYXQiOjE2MTIyNjUwODd9.FVSw2TItZ5sYJl914FlJ5JDrsRTZfyj_Cm-cuXt_450
### Send a message to one User
POST http://localhost:5000/user/5fa785b066007202a9b00819/message/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6OTg3NjU0MzIxMCwiaWQiOiI2MDE5MzY3ZWQwN2Y4YzAyZTg5MmM1OTUiLCJpYXQiOjE2MTIyNjUwODd9.FVSw2TItZ5sYJl914FlJ5JDrsRTZfyj_Cm-cuXt_450

{
    "message": "Hai, My friend",
    "sender": "5fa785ab66007202a9b00818"

}

### Edit user profile
POST http://localhost:5000/user/5fa7b8cde2908605dbaea28d/update
Content-type: application/json

{
    "fullName": "Ferrari varikkottil",
    "mobileNumber": 95447618487,
    "status": "Busy", 
    "photoUrl":"https://www.google.com"

}

### Delete user account
POST http://localhost:5000/user/5fa7b8cde2908605dbaea28d/delete
Content-type: application/json



### Create a new group
POST http://localhost:5000/group/create
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6OTg3NjU0MzIxMCwiaWQiOiI2MDE5MzY3ZWQwN2Y4YzAyZTg5MmM1OTUiLCJpYXQiOjE2MTIyNjUwODd9.FVSw2TItZ5sYJl914FlJ5JDrsRTZfyj_Cm-cuXt_450

{

    "groupName": "new dev group",
    "photoUrl": "https://www.group.com"
}

### Show all groups
GET http://localhost:5000/group/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6OTg3NjU0MzIxMCwiaWQiOiI2MDE5MzY3ZWQwN2Y4YzAyZTg5MmM1OTUiLCJpYXQiOjE2MTIyNjUwODd9.FVSw2TItZ5sYJl914FlJ5JDrsRTZfyj_Cm-cuXt_450

### Add member to group
POST http://localhost:5000/group/5fa788796fec9a02f37d635a/addmember
Content-type: application/json

{

    "userId": "5fa785ab66007202a9b00818"
}


### Send a message to the group
POST http://localhost:5000/group/5fa7885f6fec9a02f37d6358/message/new
Content-Type: application/json

{
    "message": "Hai, Folks",
    "sender": "5fa785ab66007202a9b00818"

}

### Delete Group 
POST http://localhost:5000/group/5fa7b8ffe2908605dbaea28e/delete
Content-type: application/json



### Edit Group Details
POST http://localhost:5000/group/5fa7885f6fec9a02f37d6358/update
Content-type: application/json

{
    "groupName": "Apple Boys",
    "photoUrl":"https://www.applesgroup.com"

}
